### ISSUE TITLE
Autoloading with zeitwerk results in uninitialized constant Dry::Core::ClassAttributes::IDENTITY

### ISSUE THREAD

**Issue by laugmanuel** [dry-rb/dry-configurable#157]
## Describe the bug
Using the latest version of this gem, a simple `require 'dry-configurable'` results in the following stacktrace:
```ruby
irb(main):002:0> require 'dry-configurable'
Traceback (most recent call last):
       16: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
       15: from (irb):1
       14: from (irb):2:in `rescue in irb_binding'
       13: from (irb):2:in `require'
       12: from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry-configurable.rb:3:in `<top (required)>'
       11: from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry-configurable.rb:3:in `require'
       10: from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable.rb:6:in `<top (required)>'
        9: from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable.rb:6:in `require'
        8: from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable/class_methods.rb:6:in `<top (required)>'
        7: from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable/class_methods.rb:6:in `require'
        6: from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable/dsl.rb:4:in `<top (required)>'
        5: from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable/dsl.rb:4:in `require'
        4: from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable/flags.rb:5:in `<top (required)>'
        3: from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable/flags.rb:6:in `<module:Dry>'
        2: from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable/flags.rb:11:in `<module:Configurable>'
        1: from /usr/local/bundle/gems/dry-core-0.9.0/lib/dry/core/class_attributes.rb:65:in `defines'
NameError (uninitialized constant Dry::Core::ClassAttributes::IDENTITY)
```

## To Reproduce

Install the latest release of dry-configurable and require this gem.

## Expected behavior

The gem would load fine and not throw any errors.

## My environment

- Affects my production application: YES
- Ruby version: 2.7.6 + 3.1.2
- OS: MacOS + ruby:2 Docker container

## Additional information

When requiring `dry-core` before, everything works fine:
```ruby
irb(main):001:0> require 'dry-configurable'
/usr/local/bundle/gems/dry-core-0.9.0/lib/dry/core/class_attributes.rb:65:in `defines': uninitialized constant Dry::Core::ClassAttributes::IDENTITY (NameError)

      def defines(*args, type: ::Object, coerce: IDENTITY) # rubocop:disable Metrics/PerceivedComplexity
                                                 ^^^^^^^^
	from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable/flags.rb:11:in `<module:Configurable>'
	from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable/flags.rb:6:in `<module:Dry>'
	from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable/flags.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable/dsl.rb:4:in `require'
	from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable/dsl.rb:4:in `<top (required)>'
	from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable/class_methods.rb:6:in `require'
	from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable/class_methods.rb:6:in `<top (required)>'
	from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable.rb:6:in `require'
	from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry/configurable.rb:6:in `<top (required)>'
	from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry-configurable.rb:3:in `require'
	from /usr/local/bundle/gems/dry-configurable-0.13.0/lib/dry-configurable.rb:3:in `<top (required)>'
	from (irb):1:in `require'
	from (irb):1:in `<main>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /usr/local/bin/irb:25:in `load'
	from /usr/local/bin/irb:25:in `<top (required)>'
	... 15 levels...

irb(main):002:0> require 'dry-core'
=> true
irb(main):003:0> require 'dry-configurable'
=> true
```

**Comment by solnic** [comment]
Please upgrade to dry-configurable 0.16.0 as it works with latest dry-core.
