### ISSUE TITLE
Dry::Configurable.config fails on boot (wrong number of arguments for Config.new)

### ISSUE THREAD

**Issue by backus** [dry-rb/dry-configurable#7]
I've been working on extracting `Dry::Types::Struct` to its own project. I made this change to the gemspec so I could use `Dry::Struct::VERSION`:

```diff
diff --git i/dry-struct.gemspec w/dry-struct.gemspec
index a875711..038f209 100644
--- i/dry-struct.gemspec
+++ w/dry-struct.gemspec
@@ -1,5 +1,8 @@
 # coding: utf-8
 
+root = File.expand_path(__dir__)
+require File.join(root, 'lib/dry/struct/version.rb')
+
 Gem::Specification.new do |spec|
   spec.name          = 'dry-struct'
   spec.version       = '0.0.1'
```

This bundles fine but causes a strange issue when I run the tests:

```sh
$ bundle exec rspec
/Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-configurable-0.1.6/lib/dry/configurable.rb:53:in `initialize': wrong number of arguments (given 3, expected 0) (ArgumentError)
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-configurable-0.1.6/lib/dry/configurable.rb:53:in `new'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-configurable-0.1.6/lib/dry/configurable.rb:53:in `block in config'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-configurable-0.1.6/lib/dry/configurable.rb:51:in `synchronize'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-configurable-0.1.6/lib/dry/configurable.rb:51:in `config'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-container-0.3.4/lib/dry/container/mixin.rb:91:in `register'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-logic-0.3.0/lib/dry/logic/predicate_set.rb:9:in `predicate'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-logic-0.3.0/lib/dry/logic/predicates.rb:18:in `<module:Predicates>'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-logic-0.3.0/lib/dry/logic/predicates.rb:9:in `<module:Logic>'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-logic-0.3.0/lib/dry/logic/predicates.rb:8:in `<module:Dry>'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-logic-0.3.0/lib/dry/logic/predicates.rb:7:in `<top (required)>'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-types-0.8.1/lib/dry/types/constraints.rb:2:in `require'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-types-0.8.1/lib/dry/types/constraints.rb:2:in `<top (required)>'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-types-0.8.1/lib/dry/types/constrained.rb:2:in `require'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-types-0.8.1/lib/dry/types/constrained.rb:2:in `<top (required)>'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-types-0.8.1/lib/dry/types/builder.rb:51:in `require'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-types-0.8.1/lib/dry/types/builder.rb:51:in `<top (required)>'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-types-0.8.1/lib/dry/types/definition.rb:1:in `require'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-types-0.8.1/lib/dry/types/definition.rb:1:in `<top (required)>'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-types-0.8.1/lib/dry/types.rb:13:in `require'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-types-0.8.1/lib/dry/types.rb:13:in `<top (required)>'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-types-0.8.1/lib/dry-types.rb:1:in `require'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/dry-types-0.8.1/lib/dry-types.rb:1:in `<top (required)>'
	from /Users/johnbackus/Projects/dry-struct/lib/dry/struct.rb:1:in `require'
	from /Users/johnbackus/Projects/dry-struct/lib/dry/struct.rb:1:in `<top (required)>'
	from /Users/johnbackus/Projects/dry-struct/lib/dry-struct.rb:1:in `require'
	from /Users/johnbackus/Projects/dry-struct/lib/dry-struct.rb:1:in `<top (required)>'
	from /Users/johnbackus/Projects/dry-struct/spec/spec_helper.rb:14:in `require'
	from /Users/johnbackus/Projects/dry-struct/spec/spec_helper.rb:14:in `<top (required)>'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `require'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `block in requires='
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `each'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `requires='
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `each'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:105:in `setup'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/bin/rspec:22:in `load'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/bin/rspec:22:in `<main>'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

I haven't used dry-configurable before and I am only using it now because it is part of the code I am extracting from dry-types so sorry if this is a basic issue. I'm currently pretty stumped though since the version file itself is pretty simple:

```ruby
module Dry
  class Struct
    VERSION = '0.0.1'.freeze
  end
end
```

The only place that dry-configurable is used is in the extracted errors module:

```ruby
module Dry
  class Struct
    extend Dry::Configurable

    setting :namespace, self

    Error = Class.new(TypeError)

    class RepeatedAttributeError < ArgumentError
      def initialize(key)
        super("Attribute :#{key} has already been defined")
      end
    end
  end
end
```

Here is the dry-* in question:

```sh
$ cat Gemfile.lock | grep 'dry-'
    dry-struct (0.0.1)
      dry-configurable (~> 0.1)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.2, >= 0.2.3)
      dry-types (~> 0.8, >= 0.8.1)
    dry-configurable (0.1.6)
    dry-container (0.3.4)
      dry-configurable (~> 0.1, >= 0.1.3)
    dry-equalizer (0.2.0)
    dry-logic (0.3.0)
      dry-container (~> 0.2, >= 0.2.6)
      dry-equalizer (~> 0.2)
    dry-monads (0.0.2)
    dry-types (0.8.1)
      dry-configurable (~> 0.1)
      dry-container (~> 0.3)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.3, >= 0.3.0)
      dry-monads (>= 0.0.1)
  dry-struct!
```

I tried pointing to dry-configurable master but the issue remained.

**Comment by solnic** [comment]
What happens when you change `setting :namespace, self` to `setting :namespace, :whatever`? Is the problem going away?

**Comment by backus** [comment]
@solnic nope still errors

**Comment by solnic** [comment]
This might be a nasty bug. It must have something to do with the fact that
Version file defines the Struct module. So MAYBE when it's loaded before
other gem files are loaded something weird happens on the configuration
side.

We could look into removing dry-configurable dependency btw regardless of
this bug. I'm not sure how namespace config is used though /cc @flash-gordon

**Comment by AMHOL** [comment]
@backus Thanks for reporting, please try using latest master and let me know whether that works, I'll release 0.1.7 if it does.

**Comment by backus** [comment]
@AMHOL that fixes the issue. Thanks. I have to PR a separate fix on dry-types for `Dry::Types::Result` now.

**Comment by backus** [comment]
@AMHOL ping :smile:

**Comment by AMHOL** [comment]
My bad, on it

**Comment by AMHOL** [comment]
@backus done
