### ISSUE TITLE
errors when using `setting :class` 

### ISSUE THREAD

**Issue by jtzero** [dry-rb/dry-configurable#71]
```ruby
require 'dry-configurable'

class Application
  extend Dry::Configurable
  setting :class, 'SimpleStrategy'
end

Application.config
```
```ruby
Traceback (most recent call last):
	13: from tst.rb:11:in `<main>'
	12: from /home/jtzero/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/dry-configurable-0.8.3/lib/dry/configurable.rb:148:in `config'
	11: from /home/jtzero/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/dry-configurable-0.8.3/lib/dry/configurable/config.rb:57:in `define!'
	10: from /home/jtzero/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/dry-configurable-0.8.3/lib/dry/configurable/config.rb:57:in `synchronize'
	 9: from /home/jtzero/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/dry-configurable-0.8.3/lib/dry/configurable/config.rb:61:in `block in define!'
	 8: from /home/jtzero/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/dry-configurable-0.8.3/lib/dry/configurable/config.rb:148:in `set_values!'
	 7: from /home/jtzero/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/dry-configurable-0.8.3/lib/dry/configurable/settings.rb:63:in `each'
	 6: from /home/jtzero/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/dry-configurable-0.8.3/lib/dry/configurable/settings.rb:63:in `each'
	 5: from /home/jtzero/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/dry-configurable-0.8.3/lib/dry/configurable/settings.rb:63:in `block in each'
	 4: from /home/jtzero/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/dry-configurable-0.8.3/lib/dry/configurable/config.rb:155:in `block in set_values!'
	 3: from /home/jtzero/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/dry-configurable-0.8.3/lib/dry/configurable/config.rb:57:in `define!'
	 2: from /home/jtzero/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/dry-configurable-0.8.3/lib/dry/configurable/config.rb:57:in `synchronize'
	 1: from /home/jtzero/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/dry-configurable-0.8.3/lib/dry/configurable/config.rb:61:in `block in define!'
/home/jtzero/.asdf/installs/ruby/2.6.1/lib/ruby/gems/2.6.0/gems/dry-configurable-0.8.3/lib/dry/configurable/config.rb:148:in `set_values!': undefined method `settings' for nil:NilClass (NoMethodError)
```

**Comment by solnic** [comment]
This should not crash with a vague error like this BUT it should be expected that using Ruby keywords as setting names may cause problems.

**Comment by flash-gordon** [comment]
Overriding `config.class` is not a good idea in general, we can skip method accessor in this case, only square brackets will be supported
